import type { NextPage } from 'next'
import Head from 'next/head'
import {gql, useQuery, ApolloProvider} from '@apollo/client'
import {Main} from "../layouts/main";
import {client} from "./apollo-client";


const Home: NextPage = ({ data }: any) => {


    console.log(data)

  return (
          <Main>
                  <Head>
                      <title>AniFund</title>
                      <meta name="description" content="Generated by create next app" />
                      <link rel="icon" href="/favicon.ico" />
                  </Head>
                  <main>
                      <p>{data?.Media.title.english}</p>
                      <p>{data?.Media.title.native}</p>
                  </main>
          </Main>
  )
}


export async function getServerSideProps() {
    const {data} = await client.query({
        query: gql`
            query{
                Media (id: 2355, type: ANIME) {
                    id
                    title {
                        romaji
                        english
                        native
                    }
                }
            }
        `
    })

    return {
        props: {
            data
        },
    };
}




export default Home
