import type { NextPage } from 'next'
import Head from 'next/head'
import { client } from './apollo-client'
import {gql, useQuery} from '@apollo/client'
import styles from '../styles/Home.module.css'
import {Main} from "../layouts/main";



const Home: NextPage = ({launches}: any) => {

    console.log('launches is', launches)

  return (
    <Main>
      <Head>
        <title>AniFund</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>

      </main>


    </Main>
  )
}

export async function getStaticProps() {

    const launches = [1, 1, 1]

    return {
        props: {
            launches
        }
    }
}


export default Home
